<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">
  <!-- Properties -->
  <xacro:property name="base_radius" value="0.1"/>
  <xacro:property name="base_length" value="0.05"/>
  <xacro:property name="link1_radius" value="0.05"/>
  <xacro:property name="link1_length" value="0.1"/>
  <xacro:property name="link2_size" value="0.05 0.05 0.3"/>
  <xacro:property name="link3_size" value="0.05 0.05 0.2"/>
  <xacro:property name="link4_radius" value="0.04"/>
  <xacro:property name="link4_length" value="0.08"/>
  <xacro:property name="link5_radius" value="0.035"/>
  <xacro:property name="link5_length" value="0.06"/>
  <xacro:property name="end_effector_size" value="0.03 0.1 0.02"/>

  <!-- World Frame -->
  <link name="world"/>

  <!-- Joint connecting world to base_link -->
  <joint name="world_to_base" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
  
  <!-- Materials -->
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>
  <material name="green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_length}" radius="${base_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${base_length}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint 1 -->
  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 ${base_length * 0.5}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="100" velocity="1.0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Link 1 -->
  <link name="link1">
    <visual>
      <geometry>
        <cylinder length="${link1_length}" radius="${link1_radius}"/>
      </geometry>
      <origin xyz="0 0 ${link1_length * 0.5}" rpy="0 0 0"/>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${link1_length}" radius="${link1_radius}"/>
      </geometry>
      <origin xyz="0 0 ${link1_length * 0.5}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.8"/>
      <origin xyz="0 0 ${link1_length * 0.5}" rpy="0 0 0"/>
      <inertia ixx="0.008" ixy="0.0" ixz="0.0" iyy="0.008" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Joint 2 -->
  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${link1_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.09" upper="2.09" effort="100" velocity="1.0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Link 2 -->
  <link name="link2">
    <visual>
      <geometry>
        <box size="${link2_size}"/>
      </geometry>
      <origin xyz="0 0 0.15" rpy="0 0 0"/>
      <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <box size="${link2_size}"/>
      </geometry>
      <origin xyz="0 0 0.15" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.7"/>
      <origin xyz="0 0 0.15" rpy="0 0 0"/>
      <inertia ixx="0.006" ixy="0.0" ixz="0.0" iyy="0.006" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Joint 3 -->
  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 0.3" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.09" upper="2.09" effort="100" velocity="1.0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Link 3 -->
  <link name="link3">
    <visual>
      <geometry>
        <box size="${link3_size}"/>
      </geometry>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="${link3_size}"/>
      </geometry>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.6"/>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <inertia ixx="0.005" ixy="0.0" ixz="0.0" iyy="0.005" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Joint 4 -->
  <joint name="joint4" type="revolute">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0 0 0.2" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-3.14" upper="3.14" effort="50" velocity="1.5"/>
    <dynamics damping="0.05" friction="0.05"/>
  </joint>

  <!-- Link 4 -->
  <link name="link4">
    <visual>
      <geometry>
        <cylinder length="${link4_length}" radius="${link4_radius}"/>
      </geometry>
      <origin xyz="0 0 ${link4_length * 0.5}" rpy="0 0 0"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${link4_length}" radius="${link4_radius}"/>
      </geometry>
      <origin xyz="0 0 ${link4_length * 0.5}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.4"/>
      <origin xyz="0 0 ${link4_length * 0.5}" rpy="0 0 0"/>
      <inertia ixx="0.003" ixy="0.0" ixz="0.0" iyy="0.003" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Joint 5 -->
  <joint name="joint5" type="revolute">
    <parent link="link4"/>
    <child link="link5"/>
    <origin xyz="0 0 ${link4_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-3.14" upper="3.14" effort="50" velocity="1.5"/>
    <dynamics damping="0.05" friction="0.05"/>
  </joint>

  <!-- Link 5 -->
  <link name="link5">
    <visual>
      <geometry>
        <cylinder length="${link5_length}" radius="${link5_radius}"/>
      </geometry>
      <origin xyz="0 0 ${link5_length * 0.5}" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${link5_length}" radius="${link5_radius}"/>
      </geometry>
      <origin xyz="0 0 ${link5_length * 0.5}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 ${link5_length * 0.5}" rpy="0 0 0"/>
      <inertia ixx="0.002" ixy="0.0" ixz="0.0" iyy="0.002" iyz="0.0" izz="0.0005"/>
    </inertial>
  </link>

  <!-- Joint 6 -->
  <joint name="joint6" type="revolute">
    <parent link="link5"/>
    <child link="end_effector"/>
    <origin xyz="0 0 ${link5_length}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="50" velocity="1.5"/>
    <dynamics damping="0.05" friction="0.05"/>
  </joint>

  <!-- End Effector -->
  <link name="end_effector">
    <visual>
      <geometry>
        <box size="${end_effector_size}"/>
      </geometry>
      <origin xyz="0 0 0.01" rpy="0 0 0"/>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <box size="${end_effector_size}"/>
      </geometry>
      <origin xyz="0 0 0.01" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0.01" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>
</robot>